### ISSUE TITLE
Add login endpoint

### ISSUE THREAD

**Issue by bakaydmytro** [bakaydmytro/team_seeker_be#7]
Endpoint: POST /api/login
Implement JWT token generation based on client secret, user_id, user_email.
The token expiration date should be 2 days.
Error Handling: Ensure proper error handling, such as checking for missing fields or invalid credentials.
Response Codes: Use 400 for validation errors and 401 for authentication failures to indicate proper error contexts.
 
Request Body:
{
  "email": "email@com.com",
  "password": "userpassword"
}
Response:
{
  "accessToken": "generated_access_token",
  "userId": "public_user_id"
}

**Comment by Sasha-Dektorenko** [comment]
should I just push the feat so that you can review what's wrong with the code or I need to make a pull request?
